import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';

import '../model/init_info.dart';
import '../model/micro_package.dart';
import '../model/module_info.dart';
import '../model/naming.dart';
import '../spi/parser.dart';
import '../spi/provider.dart';
import '../spi/session.dart';

/// The built-in [AnnotationParser]: reads Kaisel annotations out of Dart source
/// with the Dart analyzer's own parser.
///
/// The parse is deliberately *syntactic*: a declaration is read from its AST, not
/// from a resolved program. A host resolves neither the registry it is about to
/// generate nor the `ProfileKaiselModule` its `@KaiselInit` names — both are
/// generated by this same build — so resolution would fail exactly where the
/// generator is needed. It would also be the expensive part.
class DefaultAnnotationParser implements AnnotationParser {
  const DefaultAnnotationParser();

  @override
  void close() {}

  @override
  List<ModuleInfo> parseModules(String filePath, String source) {
    final visitor = _ModuleVisitor(filePath);
    _parse(source).accept(visitor);
    return visitor.modules;
  }

  /// Reads the `@KaiselInit` configuration [source] declares, or `null` when it
  /// declares none.
  @override
  InitInfo? parseInit(String source) {
    final visitor = _InitVisitor();
    _parse(source).accept(visitor);
    return visitor.init;
  }

  /// Reads the `@KaiselMicroPackage` declaration [source] holds, or `null` when
  /// it holds none.
  @override
  MicroPackageDeclaration? parseMicroPackage(String filePath, String source) {
    final visitor = _MicroPackageVisitor(filePath);
    _parse(source).accept(visitor);
    return visitor.microPackage;
  }
}

/// Parses [source], tolerating errors in code the generator does not need: a
/// scanned file must never fail a build over a syntax error in a part of it that
/// carries no Kaisel annotation.
CompilationUnit _parse(String source) =>
    parseString(content: source, throwIfDiagnostics: false).unit;

class _ModuleVisitor extends RecursiveAstVisitor<void> {
  _ModuleVisitor(this.filePath);

  final String filePath;
  final List<ModuleInfo> modules = [];

  @override
  void visitClassDeclaration(ClassDeclaration node) {
    final module = _moduleFromClass(node, filePath);
    if (module != null) {
      modules.add(module);
    }
    super.visitClassDeclaration(node);
  }
}

ModuleInfo? _moduleFromClass(ClassDeclaration node, String filePath) {
  final annotation = _annotationNamed(node.metadata, 'KaiselModule');
  if (annotation == null) {
    return null;
  }

  final className = _classNameOf(node);
  if (className == null) {
    return null;
  }

  final arguments = _namedArguments(annotation.arguments);
  final base = moduleBaseName(className);
  final routeType = _superclassTypeArgument(node) ?? '${base}Route';

  return ModuleInfo(
    className: className,
    routeType: routeType,
    mountName: _stringArgument(arguments, 'mount') ?? '${base}Mount',
    codecName: _typeNameOf(arguments['codec']) ??
        _codecGetterName(node) ??
        '${routeType}Codec',
    filePath: filePath,
    prefix: _stringArgument(arguments, 'prefix'),
    isInitial: _boolArgument(arguments, 'isInitial') ?? false,
  );
}

class _InitVisitor extends RecursiveAstVisitor<void> {
  InitInfo? init;

  @override
  void visitAnnotation(Annotation node) {
    if (init == null && node.name.name == 'KaiselInit') {
      final arguments = _namedArguments(node.arguments);
      init = InitInfo(
        output: _stringArgument(arguments, 'output'),
        routeClass: _stringArgument(arguments, 'routeClass') ??
            _stringArgument(arguments, 'route_class'),
        initialRoute: _stringArgument(arguments, 'initialRoute') ??
            _stringArgument(arguments, 'initial_route'),
        externalMicroPackages: _externalMicroPackageReferences(
          arguments['externalMicroPackages'] ?? arguments['external_micro_packages'],
        ),
      );
    }
    super.visitAnnotation(node);
  }
}

class _MicroPackageVisitor extends RecursiveAstVisitor<void> {
  _MicroPackageVisitor(this.filePath);

  final String filePath;
  MicroPackageDeclaration? microPackage;

  @override
  void visitAnnotation(Annotation node) {
    if (microPackage == null && node.name.name == 'KaiselMicroPackage') {
      final arguments = _namedArguments(node.arguments);
      final moduleName = _stringArgument(arguments, 'moduleName') ??
          _stringArgument(arguments, 'module_name');
      if (moduleName != null && moduleName.isNotEmpty) {
        microPackage = MicroPackageDeclaration(
          moduleName: moduleName,
          filePath: filePath,
          output: _stringArgument(arguments, 'output'),
          prefix: _stringArgument(arguments, 'prefix'),
        );
      }
    }
    super.visitAnnotation(node);
  }
}

/// Parses `[ExternalMicroPackage(ShopModule), ExternalMicroPackage(PostsModule, import: '...')]`.
List<ExternalMicroPackageReference> _externalMicroPackageReferences(
  Expression? expression,
) {
  if (expression is! ListLiteral) {
    return const [];
  }

  final references = <ExternalMicroPackageReference>[];
  for (final element in expression.elements) {
    if (_calledName(element) != 'ExternalMicroPackage') {
      continue;
    }

    final arguments = _callArguments(element)?.arguments ?? const <Argument>[];
    final positional = <Expression>[
      for (final argument in arguments)
        if (argument is! NamedArgument) argument.argumentExpression,
    ];
    if (positional.isEmpty) {
      continue;
    }

    final module = _typeNameOf(positional.first);
    if (module == null || module.isEmpty) {
      continue;
    }

    references.add(
      ExternalMicroPackageReference(
        module: module,
        import: _stringArgument(
          _namedArguments(_callArguments(element)),
          'import',
        ),
      ),
    );
  }

  return references;
}

Annotation? _annotationNamed(List<Annotation> metadata, String name) {
  for (final annotation in metadata) {
    if (annotation.name.name == name) {
      return annotation;
    }
  }
  return null;
}

/// The class's name.
///
/// `namePart` wraps either the name with its type parameters or a primary
/// constructor, so the name is read from the token that follows `class` — the
/// one position every declaration form agrees on.
String? _classNameOf(ClassDeclaration node) => node.classKeyword.next?.lexeme;

/// The route family a module extends, e.g. `ShopRoute` from
/// `extends RouteModule<ShopRoute>`.
String? _superclassTypeArgument(ClassDeclaration node) {
  final arguments = node.extendsClause?.superclass.typeArguments?.arguments;
  if (arguments == null || arguments.isEmpty) {
    return null;
  }

  final source = arguments.first.toSource();
  return source.isEmpty ? null : source;
}

/// The type a module's `codec` getter returns, e.g. `ShopRouteCodec` from
/// `ModuleStackCodec<ShopRoute> get codec => const ShopRouteCodec();`.
String? _codecGetterName(ClassDeclaration node) {
  for (final member in node.body.members) {
    if (member is! MethodDeclaration ||
        !member.isGetter ||
        member.name.lexeme != 'codec') {
      continue;
    }

    final body = member.body;
    if (body is ExpressionFunctionBody) {
      return _typeNameOf(body.expression);
    }
  }
  return null;
}

/// The type name behind an expression that names a type: a plain identifier
/// (`ShopRouteCodec`), an invocation of one (`ShopRouteCodec()`, `const
/// ShopRouteCodec()`), or a generic type literal.
String? _typeNameOf(AstNode? expression) =>
    _calledName(expression) ??
    switch (expression) {
      TypeLiteral(:final type) => type.name.lexeme,
      SimpleIdentifier(:final name) => name,
      PrefixedIdentifier(:final identifier) => identifier.name,
      _ => null,
    };

/// The name of the class or function an expression calls, without its type
/// arguments or prefix.
///
/// A call parses as a `MethodInvocation` unless it is written with `new` or
/// `const`, so both forms have to be read.
String? _calledName(AstNode? expression) => switch (expression) {
      MethodInvocation(:final methodName) => methodName.name,
      InstanceCreationExpression(:final constructorName) =>
        constructorName.type.name.lexeme,
      _ => null,
    };

/// The arguments of a call, in either of the forms [_calledName] reads.
ArgumentList? _callArguments(AstNode? expression) => switch (expression) {
      MethodInvocation(:final argumentList) => argumentList,
      InstanceCreationExpression(:final argumentList) => argumentList,
      _ => null,
    };

/// The named arguments of an annotation or constructor call, by name.
Map<String, Expression> _namedArguments(ArgumentList? arguments) {
  final result = <String, Expression>{};
  for (final argument in arguments?.arguments ?? const <Argument>[]) {
    if (argument is NamedArgument) {
      result[argument.name.lexeme] = argument.argumentExpression;
    }
  }
  return result;
}

String? _stringArgument(Map<String, Expression> arguments, String name) {
  final expression = arguments[name];
  return expression is StringLiteral ? expression.stringValue : null;
}

bool? _boolArgument(Map<String, Expression> arguments, String name) {
  final expression = arguments[name];
  return expression is BooleanLiteral ? expression.value : null;
}

/// Creates the built-in [AnnotationParser].
class DefaultAnnotationParserFactory implements AnnotationParserFactory {
  const DefaultAnnotationParserFactory();

  @override
  String get id => 'default';

  @override
  int get order => kaiselProviderOrder;

  @override
  AnnotationParser create(KaiselSession session) => const DefaultAnnotationParser();
}
