import 'package:spi/spi.dart';

import '../model/micro_package.dart';
import '../model/module_info.dart';
import '../spi/emitter.dart';

/// The built-in [RegistryEmitter]: the host's module registry, the sealed route
/// hierarchy, the page builder, the URL mounts and the router config an app runs
/// on.
class DefaultRegistryEmitter implements RegistryEmitter {
  const DefaultRegistryEmitter({required this.imports});

  final ImportEmitter imports;

  @override
  void close() {}

  @override
  String write({
    required List<ModuleInfo> modules,
    required String routeClass,
    required String? initialRouteOverride,
    required List<MicroPackageInfo> microPackages,
    required String packageName,
    required String libDir,
  }) {
    final localFiles = _uniqueSorted([for (final module in modules) module.filePath]);
    final localAliases = imports.aliasesFor(localFiles, '_i');
    final packageAliases = [
      for (var index = 0; index < microPackages.length; index++) '_mp${index + 1}',
    ];

    // Routed modules, longest prefix first, so an overlapping mount (`/shop/v2`)
    // is tried before the mount it nests inside (`/shop`).
    final routed = [for (final module in modules) if (module.isRouted) module]
      ..sort(_byPrefixLengthThenName);

    final initialMount = _initialMount(modules, microPackages, initialRouteOverride);
    final mountNames = _mountNames(modules, microPackages);

    final buffer = StringBuffer();
    buffer.write('// GENERATED CODE - DO NOT MODIFY BY HAND\n');
    buffer.write('// Generated by kaisel_generator\n\n');

    buffer.write("import 'package:flutter/widgets.dart';\n");
    buffer.write("import 'package:kaisel/kaisel.dart';\n");
    if (microPackages.isNotEmpty) {
      buffer.write("import 'package:kaisel_generator/micro_mount.dart';\n");
    }
    buffer.write('\n');

    imports.writeImports(buffer, [
      for (var index = 0; index < microPackages.length; index++)
        (uri: microPackages[index].importUri, alias: packageAliases[index]),
      for (final file in localFiles)
        (
          uri: imports.packageUri(packageName: packageName, libDir: libDir, file: file),
          alias: localAliases[file]!,
        ),
    ]);
    buffer.write('\n');

    buffer.write("// Host's sealed route hierarchy: one marker mount per feature module.\n");
    buffer.write('sealed class $routeClass extends KaiselRoute {\n');
    buffer.write('  const $routeClass();\n');
    buffer.write('}\n\n');

    for (final mountName in mountNames) {
      buffer.write('final class $mountName extends $routeClass {\n');
      buffer.write('  const $mountName();\n');
      buffer.write('}\n\n');
    }

    buffer.write('/// The default initial route for the host router.\n');
    buffer.write('const $routeClass kInitialAppRoute = $initialMount();\n\n');

    buffer.write('/// Dispatches each feature module inside a `KaiselModuleMount`.\n');
    buffer.write(
      'Widget buildAppModulePage(BuildContext context, $routeClass route) => switch (route) {\n',
    );
    for (final module in modules) {
      final alias = localAliases[module.filePath]!;
      buffer.write(
        '  ${module.mountName}() => const KaiselModuleMount<$alias.${module.routeType}>'
        '(module: $alias.${module.className}()),\n',
      );
    }
    for (var index = 0; index < microPackages.length; index++) {
      final package = microPackages[index];
      for (final mount in package.mounts) {
        buffer.write(
          '  ${mount.marker}() => ${packageAliases[index]}.${package.className}'
          '.${mount.fieldName}.page,\n',
        );
      }
    }
    buffer.write('};\n\n');

    buffer.write('/// Declarative module mounts for `ConfigCodecWithModules`.\n');
    buffer.write(
      '${microPackages.isEmpty ? 'const' : 'final'} List<ModuleMount<$routeClass>> '
      'appModuleMounts = [\n',
    );
    for (final module in routed) {
      final alias = localAliases[module.filePath]!;
      buffer.write('  ModuleMount(\n');
      buffer.write('    mountRoute: ${module.mountName}(),\n');
      buffer.write("    prefix: '${module.prefix}',\n");
      buffer.write('    codec: $alias.${module.codecName}(),\n');
      buffer.write('  ),\n');
    }
    for (var index = 0; index < microPackages.length; index++) {
      final package = microPackages[index];
      for (final mount in package.mounts.where((mount) => mount.isRouted)) {
        buffer.write(
          '  ${packageAliases[index]}.${package.className}.${mount.fieldName}'
          '.moduleMount(const ${mount.marker}()),\n',
        );
      }
    }
    buffer.write('];\n\n');

    buffer.write('/// Encodes host mount markers to their canonical URLs.\n');
    buffer.write('Uri? encodeAppModuleRoute($routeClass route) => switch (route) {\n');
    for (final module in modules) {
      buffer.write(
        "  ${module.mountName}() => Uri(path: '${module.prefix ?? '/'}'),\n",
      );
    }
    for (var index = 0; index < microPackages.length; index++) {
      final package = microPackages[index];
      for (final mount in package.mounts) {
        buffer.write(
          '  ${mount.marker}() => ${packageAliases[index]}.${package.className}'
          '.${mount.fieldName}.url,\n',
        );
      }
    }
    buffer.write('};\n\n');

    buffer.write('/// Default host codec delegating unmounted paths to the initial route.\n');
    buffer.write('class DefaultBaseAppCodec extends KaiselConfigCodec<$routeClass> {\n');
    buffer.write('  const DefaultBaseAppCodec();\n\n');
    buffer.write('  @override\n');
    buffer.write('  KaiselConfig<$routeClass>? decode(Uri uri) {\n');
    buffer.write('    final segments = uri.pathSegments\n');
    buffer.write('        .where((segment) => segment.isNotEmpty)\n');
    buffer.write('        .toList(growable: false);\n\n');
    buffer.write('    return switch (segments) {\n');
    buffer.write('      [] => KaiselConfig(mainStack: const [kInitialAppRoute]),\n');
    buffer.write('      _ => null,\n');
    buffer.write('    };\n');
    buffer.write('  }\n\n');
    buffer.write('  @override\n');
    buffer.write('  Uri encode(KaiselConfig<$routeClass> config) {\n');
    buffer.write('    final uri = encodeAppModuleRoute(config.mainStack.last);\n');
    buffer.write("    return uri ?? Uri(path: '/');\n");
    buffer.write('  }\n');
    buffer.write('}\n\n');

    buffer.write(
      '/// Complete composite URL codec bundling `DefaultBaseAppCodec` and `appModuleMounts`.\n',
    );
    buffer.write(
      '${microPackages.isEmpty ? 'const' : 'final'} defaultAppCodec = '
      'ConfigCodecWithModules<$routeClass>(\n',
    );
    buffer.write(
      microPackages.isEmpty
          ? '  baseCodec: DefaultBaseAppCodec(),\n'
          : '  baseCodec: const DefaultBaseAppCodec(),\n',
    );
    buffer.write('  modules: appModuleMounts,\n');
    buffer.write(');\n\n');

    buffer.write('/// Ready-to-use default router configuration for the host app.\n');
    buffer.write('final defaultAppRouterConfig = KaiselRouterConfig<$routeClass>(\n');
    buffer.write('  initial: kInitialAppRoute,\n');
    buffer.write('  builder: buildAppModulePage,\n');
    buffer.write('  codec: defaultAppCodec,\n');
    buffer.write(');\n\n');

    buffer.write('/// Convenience factory for customizing host router configuration.\n');
    buffer.write('KaiselRouterConfig<$routeClass> createAppRouterConfig({\n');
    buffer.write('  $routeClass? initial,\n');
    buffer.write('  KaiselPageBuilder<$routeClass>? builder,\n');
    buffer.write('  KaiselConfigCodec<$routeClass>? codec,\n');
    buffer.write('}) =>\n');
    buffer.write('    KaiselRouterConfig<$routeClass>(\n');
    buffer.write('      initial: initial ?? kInitialAppRoute,\n');
    buffer.write('      builder: builder ?? buildAppModulePage,\n');
    buffer.write('      codec: codec ?? defaultAppCodec,\n');
    buffer.write('    );\n');

    return buffer.toString();
  }

  /// The mount the host lands on: an explicit `initialRoute`, else the module
  /// marked `isInitial`, else a micro-package's initial mount, else the first
  /// module.
  String _initialMount(
    List<ModuleInfo> modules,
    List<MicroPackageInfo> microPackages,
    String? override,
  ) {
    if (override != null && override.isNotEmpty) {
      return override;
    }
    for (final module in modules) {
      if (module.isInitial) {
        return module.mountName;
      }
    }
    for (final package in microPackages) {
      final mount = package.initialMount;
      if (mount != null) {
        return mount.marker;
      }
    }
    return modules.isEmpty ? 'HomeMount' : modules.first.mountName;
  }

  /// Every marker route the host declares: its own modules first, then the mounts
  /// its micro-packages contribute.
  List<String> _mountNames(
    List<ModuleInfo> modules,
    List<MicroPackageInfo> microPackages,
  ) {
    final names = <String>[];
    final seen = <String>{};
    for (final module in modules) {
      if (seen.add(module.mountName)) {
        names.add(module.mountName);
      }
    }
    for (final package in microPackages) {
      for (final mount in package.mounts) {
        if (seen.add(mount.marker)) {
          names.add(mount.marker);
        }
      }
    }
    return names;
  }

  int _byPrefixLengthThenName(ModuleInfo a, ModuleInfo b) {
    final byLength = b.prefix!.length.compareTo(a.prefix!.length);
    return byLength != 0 ? byLength : a.mountName.compareTo(b.mountName);
  }

  List<String> _uniqueSorted(List<String> values) =>
      values.toSet().toList()..sort();
}

/// Creates the built-in [RegistryEmitter], with the session's [ImportEmitter].
class DefaultRegistryEmitterFactory implements RegistryEmitterFactory {
  const DefaultRegistryEmitterFactory();

  @override
  String get id => 'default';

  @override
  int get order => defaultProviderOrder;

  @override
  ProviderScope get scope => ProviderScope.session;

  @override
  RegistryEmitter create(ProviderSession session) => DefaultRegistryEmitter(
        imports: session.provider(ImportEmitterSpi.instance),
      );
}
