import '../model/module_info.dart';
import '../model/naming.dart';
import 'import_emitter.dart';

/// Emits a micro-package manifest: one registry class declaring what the package
/// contributes, for a host to bind to its own marker routes.
class ManifestEmitter {
  const ManifestEmitter({this.imports = const ImportEmitter()});

  final ImportEmitter imports;

  /// Writes the manifest of the package module named [moduleName].
  String write({
    required String moduleName,
    required List<ModuleInfo> modules,
    required String packageName,
    required String libDir,
    required String? basePrefix,
  }) {
    final files = _uniqueSorted([for (final module in modules) module.filePath]);
    final aliases = imports.aliasesFor(files, 'i');
    final className = '${moduleName}KaiselModule';

    final buffer = StringBuffer();
    buffer.write('// GENERATED CODE - DO NOT MODIFY BY HAND\n');
    buffer.write('// Generated by kaisel_generator\n\n');

    buffer.write("import 'package:kaisel_generator/micro_mount.dart';\n\n");

    imports.writeImports(buffer, [
      for (final file in files)
        (
          uri: imports.packageUri(packageName: packageName, libDir: libDir, file: file),
          alias: aliases[file]!,
        ),
    ]);
    buffer.write('\n');

    buffer.write('/// Micro-package module registry for `$moduleName`.\n');
    buffer.write('///\n');
    buffer.write('/// Each declaration is a mount the host binds to one of its own marker\n');
    buffer.write('/// routes, so no mount is ever resolved by name.\n');
    buffer.write('abstract final class $className {\n');

    for (var index = 0; index < modules.length; index++) {
      final module = modules[index];
      final alias = aliases[module.filePath]!;
      final routeType = '$alias.${module.routeType}';
      final fieldName = toCamelCase(module.mountName);

      if (index > 0) {
        buffer.write('\n');
      }
      buffer.write('  /// The mount this package contributes for `${module.mountName}`.\n');
      buffer.write('  static const KaiselMicroMount<$routeType> $fieldName =\n');
      buffer.write('      KaiselMicroMount<$routeType>(\n');
      if (module.prefix != null) {
        buffer.write("    prefix: '${_effectivePrefix(basePrefix, module.prefix!)}',\n");
      }
      buffer.write('    module: $alias.${module.className}(),\n');
      buffer.write('    codec: $alias.${module.codecName}(),\n');
      if (module.isInitial) {
        buffer.write('    isInitial: true,\n');
      }
      buffer.write('  );\n');
    }

    buffer.write('}\n');

    return buffer.toString();
  }

  /// Joins a micro-package base prefix with a module's own prefix:
  /// `'/shop'` + `'/products'` → `'/shop/products'`.
  String _effectivePrefix(String? basePrefix, String rawPrefix) {
    if (basePrefix == null) {
      return rawPrefix;
    }

    return '${basePrefix.replaceAll(RegExp(r'/+$'), '')}/'
        '${rawPrefix.replaceFirst(RegExp(r'^/+'), '')}';
  }

  List<String> _uniqueSorted(List<String> values) =>
      values.toSet().toList()..sort();
}
