import 'package:analyzer/dart/analysis/utilities.dart';
import 'package:analyzer/dart/ast/ast.dart';
import 'package:analyzer/dart/ast/visitor.dart';

import '../helper/ast.dart';
import '../helper/naming.dart';
import '../models/config.dart';
import '../models/scan.dart';

/// Reads Kaisel annotations out of source.
///
/// The default reads Dart source text; a test that needs a fixture implements
/// this instead. Callers hand it the file path (for the metadata it records) and
/// the source.
abstract interface class AnnotationParser {
  /// Reads every `@KaiselModule` class declared in [source].
  List<ModuleInfo> parseModules(String filePath, String source);

  /// Reads the `@KaiselInit` configuration [source] declares, or `null` when it
  /// declares none.
  InitInfo? parseInit(String source);

  /// Reads the `@KaiselMicroPackage` declaration [source] holds, or `null` when
  /// it holds none.
  MicroPackageDeclaration? parseMicroPackage(String filePath, String source);
}

/// The default [AnnotationParser]: reads Kaisel annotations out of Dart source
/// with the Dart analyzer's own parser.
///
/// The parse is deliberately *syntactic*: a declaration is read from its AST, not
/// from a resolved program. A host resolves neither the registry it is about to
/// generate nor the `ProfileKaiselModule` its `@KaiselInit` names — both are
/// generated by this same build — so resolution would fail exactly where the
/// generator is needed. It would also be the expensive part.
class DefaultAnnotationParser implements AnnotationParser {
  const DefaultAnnotationParser();

  @override
  List<ModuleInfo> parseModules(String filePath, String source) {
    final visitor = _ModuleVisitor(filePath);
    _parse(source).accept(visitor);
    return visitor.modules;
  }

  @override
  InitInfo? parseInit(String source) {
    final visitor = _InitVisitor();
    _parse(source).accept(visitor);
    return visitor.init;
  }

  @override
  MicroPackageDeclaration? parseMicroPackage(String filePath, String source) {
    final visitor = _MicroPackageVisitor(filePath);
    _parse(source).accept(visitor);
    return visitor.microPackage;
  }
}

/// Parses [source], tolerating errors in code the generator does not need: a
/// scanned file must never fail a build over a syntax error in a part of it that
/// carries no Kaisel annotation.
CompilationUnit _parse(String source) =>
    parseString(content: source, throwIfDiagnostics: false).unit;

class _ModuleVisitor extends RecursiveAstVisitor<void> {
  _ModuleVisitor(this.filePath);

  final String filePath;
  final List<ModuleInfo> modules = [];

  @override
  void visitClassDeclaration(ClassDeclaration node) {
    final module = _moduleFromClass(node, filePath);
    if (module != null) {
      modules.add(module);
    }
    super.visitClassDeclaration(node);
  }
}

ModuleInfo? _moduleFromClass(ClassDeclaration node, String filePath) {
  final annotation = annotationNamed(node.metadata, 'KaiselModule');
  if (annotation == null) {
    return null;
  }

  final className = classNameOf(node);
  if (className == null) {
    return null;
  }

  final arguments = namedArguments(annotation.arguments);
  final base = moduleBaseName(className);
  final routeType = _superclassTypeArgument(node) ?? '${base}Route';

  return ModuleInfo(
    className: className,
    routeType: routeType,
    mountName: stringArgument(arguments, 'mount') ?? '${base}Mount',
    codecName: typeNameOf(arguments['codec']) ??
        _codecGetterName(node) ??
        '${routeType}Codec',
    filePath: filePath,
    prefix: stringArgument(arguments, 'prefix'),
    isInitial: boolArgument(arguments, 'isInitial') ?? false,
  );
}

class _InitVisitor extends RecursiveAstVisitor<void> {
  InitInfo? init;

  @override
  void visitAnnotation(Annotation node) {
    if (init == null && node.name.name == 'KaiselInit') {
      final arguments = namedArguments(node.arguments);
      init = InitInfo(
        output: stringArgument(arguments, 'output'),
        routeClass: stringArgument(arguments, 'routeClass') ??
            stringArgument(arguments, 'route_class'),
        initialRoute: stringArgument(arguments, 'initialRoute') ??
            stringArgument(arguments, 'initial_route'),
        externalMicroPackages: _externalMicroPackageReferences(
          arguments['externalMicroPackages'] ??
              arguments['external_micro_packages'],
        ),
      );
    }
    super.visitAnnotation(node);
  }
}

class _MicroPackageVisitor extends RecursiveAstVisitor<void> {
  _MicroPackageVisitor(this.filePath);

  final String filePath;
  MicroPackageDeclaration? microPackage;

  @override
  void visitAnnotation(Annotation node) {
    if (microPackage == null && node.name.name == 'KaiselMicroPackage') {
      final arguments = namedArguments(node.arguments);
      final moduleName = stringArgument(arguments, 'moduleName') ??
          stringArgument(arguments, 'module_name');
      if (moduleName != null && moduleName.isNotEmpty) {
        microPackage = MicroPackageDeclaration(
          moduleName: moduleName,
          filePath: filePath,
          output: stringArgument(arguments, 'output'),
          prefix: stringArgument(arguments, 'prefix'),
        );
      }
    }
    super.visitAnnotation(node);
  }
}

/// Parses `[ExternalMicroPackage(ShopModule), ExternalMicroPackage(PostsModule, import: '...')]`.
List<ExternalMicroPackageReference> _externalMicroPackageReferences(
  Expression? expression,
) {
  if (expression is! ListLiteral) {
    return const [];
  }

  final references = <ExternalMicroPackageReference>[];
  for (final element in expression.elements) {
    if (calledName(element) != 'ExternalMicroPackage') {
      continue;
    }

    final arguments = callArguments(element)?.arguments ?? const <Argument>[];
    final positional = <Expression>[
      for (final argument in arguments)
        if (argument is! NamedArgument) argument.argumentExpression,
    ];
    if (positional.isEmpty) {
      continue;
    }

    final module = typeNameOf(positional.first);
    if (module == null || module.isEmpty) {
      continue;
    }

    references.add(
      ExternalMicroPackageReference(
        module: module,
        import:
            stringArgument(namedArguments(callArguments(element)), 'import'),
      ),
    );
  }

  return references;
}

/// The route family a module extends, e.g. `ShopRoute` from
/// `extends RouteModule<ShopRoute>`.
String? _superclassTypeArgument(ClassDeclaration node) {
  final arguments = node.extendsClause?.superclass.typeArguments?.arguments;
  if (arguments == null || arguments.isEmpty) {
    return null;
  }

  final source = arguments.first.toSource();
  return source.isEmpty ? null : source;
}

/// The type a module's `codec` getter returns, e.g. `ShopRouteCodec` from
/// `ModuleStackCodec<ShopRoute> get codec => const ShopRouteCodec();`.
String? _codecGetterName(ClassDeclaration node) {
  for (final member in node.body.members) {
    if (member is! MethodDeclaration ||
        !member.isGetter ||
        member.name.lexeme != 'codec') {
      continue;
    }

    final body = member.body;
    if (body is ExpressionFunctionBody) {
      return typeNameOf(body.expression);
    }
  }
  return null;
}
