import 'package:path/path.dart' as p;

import '../helper/naming.dart';
import '../models/scan.dart';

/// Writes the imports a generated file opens with.
///
/// Implement this to change how generated files import what they compose — a
/// different alias scheme, relative imports, a fixed header.
abstract interface class ImportEmitter {
  /// The aliases for [keys], numbered `1..n` in the order given.
  Map<String, String> aliasesFor(List<String> keys, String prefix);

  /// Writes `import '<uri>' as <alias>;` for each of [aliasedImports].
  void writeImports(
    StringBuffer buffer,
    List<({String uri, String alias})> aliasedImports,
  );

  /// A `package:` import for a file inside the package.
  String packageUri({
    required String packageName,
    required String libDir,
    required String file,
  });
}

/// The default [ImportEmitter].
///
/// Every generated file imports the modules it composes under an alias — `_i1`
/// for the host's own modules, `i1` inside a manifest, `_mp1` for the packages a
/// host composes — so two features that happen to pick the same symbol name
/// cannot collide. Aliases are assigned in the order the imports are registered,
/// and callers register the files sorted, so generated output does not depend on
/// the order the filesystem handed the files over.
class DefaultImportEmitter implements ImportEmitter {
  const DefaultImportEmitter();

  @override
  Map<String, String> aliasesFor(List<String> keys, String prefix) => {
        for (var index = 0; index < keys.length; index++)
          keys[index]: '$prefix${index + 1}',
      };

  @override
  void writeImports(
    StringBuffer buffer,
    List<({String uri, String alias})> aliasedImports,
  ) {
    for (final import in aliasedImports) {
      buffer.write("import '${import.uri}' as ${import.alias};\n");
    }
  }

  /// A `package:` import for a file inside the package, so generated code does
  /// not depend on where it sits relative to what it imports.
  ///
  /// Falls back to the file's own path when it lies outside [libDir] or the
  /// package name is unknown.
  @override
  String packageUri({
    required String packageName,
    required String libDir,
    required String file,
  }) {
    final posixFile = file.replaceAll(r'\', '/');
    if (packageName.isEmpty) {
      return posixFile;
    }

    final relative = p.relative(file, from: libDir).replaceAll(r'\', '/');
    if (relative == '..' || relative.startsWith('../')) {
      return posixFile;
    }

    return 'package:$packageName/$relative';
  }
}

/// Writes one registry class declaring what a micro-package contributes, for a
/// host to bind to its own marker routes.
abstract interface class ManifestEmitter {
  /// Writes the manifest of the package module named [moduleName].
  String write({
    required String moduleName,
    required List<ModuleInfo> modules,
    required String packageName,
    required String libDir,
    required String? basePrefix,
  });
}

/// The default [ManifestEmitter]: one registry class declaring what a
/// micro-package contributes, for a host to bind to its own marker routes.
class DefaultManifestEmitter implements ManifestEmitter {
  const DefaultManifestEmitter({required this.imports});

  final ImportEmitter imports;

  @override
  String write({
    required String moduleName,
    required List<ModuleInfo> modules,
    required String packageName,
    required String libDir,
    required String? basePrefix,
  }) {
    final files =
        _uniqueSorted([for (final module in modules) module.filePath]);
    final aliases = imports.aliasesFor(files, 'i');
    final className = '${moduleName}KaiselModule';

    final buffer = StringBuffer();
    buffer.write('// GENERATED CODE - DO NOT MODIFY BY HAND\n');
    buffer.write('// Generated by kaisel_generator\n\n');

    buffer.write("import 'package:kaisel_generator/micro_mount.dart';\n\n");

    imports.writeImports(buffer, [
      for (final file in files)
        (
          uri: imports.packageUri(
            packageName: packageName,
            libDir: libDir,
            file: file,
          ),
          alias: aliases[file]!,
        ),
    ]);
    buffer.write('\n');

    buffer.write('/// Micro-package module registry for `$moduleName`.\n');
    buffer.write('///\n');
    buffer.write(
        '/// Each declaration is a mount the host binds to one of its own marker\n');
    buffer.write('/// routes, so no mount is ever resolved by name.\n');
    buffer.write('abstract final class $className {\n');

    for (var index = 0; index < modules.length; index++) {
      final module = modules[index];
      final alias = aliases[module.filePath]!;
      final routeType = '$alias.${module.routeType}';
      final fieldName = toCamelCase(module.mountName);

      if (index > 0) {
        buffer.write('\n');
      }
      buffer.write(
          '  /// The mount this package contributes for `${module.mountName}`.\n');
      buffer
          .write('  static const KaiselMicroMount<$routeType> $fieldName =\n');
      buffer.write('      KaiselMicroMount<$routeType>(\n');
      if (module.prefix != null) {
        buffer.write(
          "    prefix: '${_effectivePrefix(basePrefix, module.prefix!)}',\n",
        );
      }
      buffer.write('    module: $alias.${module.className}(),\n');
      buffer.write('    codec: $alias.${module.codecName}(),\n');
      if (module.isInitial) {
        buffer.write('    isInitial: true,\n');
      }
      buffer.write('  );\n');
    }

    buffer.write('}\n');

    return buffer.toString();
  }

  /// Joins a micro-package base prefix with a module's own prefix:
  /// `'/shop'` + `'/products'` → `'/shop/products'`.
  String _effectivePrefix(String? basePrefix, String rawPrefix) {
    if (basePrefix == null) {
      return rawPrefix;
    }

    return '${basePrefix.replaceAll(RegExp(r'/+$'), '')}/'
        '${rawPrefix.replaceFirst(RegExp(r'^/+'), '')}';
  }

  List<String> _uniqueSorted(List<String> values) =>
      values.toSet().toList()..sort();
}
