use std::collections::HashMap;
use std::path::{Path, PathBuf};
use pathdiff::diff_paths;

use crate::parser::ModuleMetadata;

pub fn generate_dart_code(
    modules: &[ModuleMetadata],
    output_file: &Path,
) -> String {
    let output_dir = output_file.parent().unwrap_or(Path::new("."));

    // Map each unique file_path to an import alias (_i1, _i2, ...)
    let mut unique_files: Vec<PathBuf> = modules
        .iter()
        .map(|m| m.file_path.clone())
        .collect();
    unique_files.sort();
    unique_files.dedup();

    let file_to_alias: HashMap<PathBuf, String> = unique_files
        .iter()
        .enumerate()
        .map(|(idx, path): (usize, &PathBuf)| (path.clone(), format!("_i{}", idx + 1)))
        .collect();

    // Determine initial module
    let initial_module = modules
        .iter()
        .find(|m| m.is_initial)
        .or_else(|| modules.first());

    let initial_mount = initial_module
        .map(|m| m.mount_name.as_str())
        .unwrap_or("HomeMount");

    // Modules with URL prefix, sorted by prefix length descending
    let mut routed_modules: Vec<&ModuleMetadata> = modules
        .iter()
        .filter(|m| m.prefix.is_some())
        .collect();
    routed_modules.sort_by(|a, b| {
        let len_a = a.prefix.as_ref().map(|p: &String| p.len()).unwrap_or(0);
        let len_b = b.prefix.as_ref().map(|p: &String| p.len()).unwrap_or(0);
        len_b.cmp(&len_a).then_with(|| a.mount_name.cmp(&b.mount_name))
    });

    let mut buf = String::with_capacity(4096);

    // Header
    buf.push_str("// GENERATED CODE - DO NOT MODIFY BY HAND\n");
    buf.push_str("// Generated by kaisel_generator\n\n");

    // Core Imports
    buf.push_str("import 'package:flutter/widgets.dart';\n");
    buf.push_str("import 'package:kaisel/kaisel.dart';\n\n");

    // Feature Module Imports with import aliases
    for file_path in &unique_files {
        let alias = &file_to_alias[file_path];
        let rel = diff_paths(file_path.as_path(), output_dir).unwrap_or_else(|| file_path.clone());
        let rel_str = rel.to_string_lossy().replace('\\', "/");
        let clean_rel = if !rel_str.starts_with('.') {
            format!("./{rel_str}")
        } else {
            rel_str
        };
        buf.push_str(&format!("import '{clean_rel}' as {alias};\n"));
    }
    buf.push('\n');

    // AppRoute Sealed Class
    buf.push_str("// Host's sealed route hierarchy: one marker mount per feature module.\n");
    buf.push_str("sealed class AppRoute extends KaiselRoute {\n");
    buf.push_str("  const AppRoute();\n");
    buf.push_str("}\n\n");

    // Individual Mount Subclasses
    for m in modules {
        buf.push_str(&format!(
            "final class {} extends AppRoute {{\n  const {}();\n}}\n\n",
            m.mount_name, m.mount_name
        ));
    }

    // Initial App Route Constant
    buf.push_str("/// The default initial route for the host router.\n");
    buf.push_str(&format!(
        "const AppRoute kInitialAppRoute = {}();\n\n",
        initial_mount
    ));

    // Page Builder Switch
    buf.push_str("/// Dispatches each feature module inside a `KaiselModuleMount`.\n");
    buf.push_str("Widget buildAppModulePage(BuildContext context, AppRoute route) => switch (route) {\n");
    for m in modules {
        let alias = &file_to_alias[&m.file_path];
        buf.push_str(&format!(
            "  {}() => const KaiselModuleMount<{}.{}>(module: {}.{}()),\n",
            m.mount_name, alias, m.route_type, alias, m.class_name
        ));
    }
    buf.push_str("};\n\n");

    // Module Mounts List
    buf.push_str("/// Declarative module mounts for `ConfigCodecWithModules`.\n");
    buf.push_str("const List<ModuleMount<AppRoute>> appModuleMounts = [\n");
    for m in &routed_modules {
        let alias = &file_to_alias[&m.file_path];
        let prefix = m.prefix.as_ref().unwrap();
        let codec_expr = match &m.codec_name {
            Some(c) => format!("{}.{}()", alias, c),
            None => format!("{}.{}Codec()", alias, m.route_type),
        };
        buf.push_str("  ModuleMount(\n");
        buf.push_str(&format!("    mountRoute: {}(),\n", m.mount_name));
        buf.push_str(&format!("    prefix: '{}',\n", prefix));
        buf.push_str(&format!("    codec: {},\n", codec_expr));
        buf.push_str("  ),\n");
    }
    buf.push_str("];\n\n");

    // Route Encoder Helper
    buf.push_str("/// Encodes host mount markers to their canonical URLs.\n");
    buf.push_str("Uri? encodeAppModuleRoute(AppRoute route) => switch (route) {\n");
    for m in modules {
        let path = match &m.prefix {
            Some(p) => p.as_str(),
            None => "/",
        };
        buf.push_str(&format!(
            "  {}() => Uri(path: '{}'),\n",
            m.mount_name, path
        ));
    }
    buf.push_str("};\n\n");

    // Default Base App Codec
    buf.push_str("/// Default host codec delegating unmounted paths to the initial route.\n");
    buf.push_str("class DefaultBaseAppCodec extends KaiselConfigCodec<AppRoute> {\n");
    buf.push_str("  const DefaultBaseAppCodec();\n\n");
    buf.push_str("  @override\n");
    buf.push_str("  KaiselConfig<AppRoute>? decode(Uri uri) {\n");
    buf.push_str("    final segments = uri.pathSegments\n");
    buf.push_str("        .where((segment) => segment.isNotEmpty)\n");
    buf.push_str("        .toList(growable: false);\n\n");
    buf.push_str("    return switch (segments) {\n");
    buf.push_str("      [] => KaiselConfig(mainStack: const [kInitialAppRoute]),\n");
    buf.push_str("      _ => null,\n");
    buf.push_str("    };\n");
    buf.push_str("  }\n\n");
    buf.push_str("  @override\n");
    buf.push_str("  Uri encode(KaiselConfig<AppRoute> config) {\n");
    buf.push_str("    final uri = encodeAppModuleRoute(config.mainStack.last);\n");
    buf.push_str("    return uri ?? Uri(path: '/');\n");
    buf.push_str("  }\n");
    buf.push_str("}\n\n");

    // Default Complete App Codec
    buf.push_str("/// Complete composite URL codec bundling `DefaultBaseAppCodec` and `appModuleMounts`.\n");
    buf.push_str("const defaultAppCodec = ConfigCodecWithModules<AppRoute>(\n");
    buf.push_str("  baseCodec: DefaultBaseAppCodec(),\n");
    buf.push_str("  modules: appModuleMounts,\n");
    buf.push_str(");\n\n");

    // Backwards-compatible codec alias
    buf.push_str("/// Backwards-compatible alias for `defaultAppCodec`.\n");
    buf.push_str("const appCodec = defaultAppCodec;\n\n");

    // Default Router Config
    buf.push_str("/// Ready-to-use default router configuration for the host app.\n");
    buf.push_str("final defaultAppRouterConfig = KaiselRouterConfig<AppRoute>(\n");
    buf.push_str("  initial: kInitialAppRoute,\n");
    buf.push_str("  builder: buildAppModulePage,\n");
    buf.push_str("  codec: defaultAppCodec,\n");
    buf.push_str(");\n\n");

    // Custom router config factory
    buf.push_str("/// Convenience factory for customizing host router configuration.\n");
    buf.push_str("KaiselRouterConfig<AppRoute> createAppRouterConfig({\n");
    buf.push_str("  AppRoute? initial,\n");
    buf.push_str("  KaiselPageBuilder<AppRoute>? builder,\n");
    buf.push_str("  KaiselConfigCodec<AppRoute>? codec,\n");
    buf.push_str("}) =>\n");
    buf.push_str("    KaiselRouterConfig<AppRoute>(\n");
    buf.push_str("      initial: initial ?? kInitialAppRoute,\n");
    buf.push_str("      builder: builder ?? buildAppModulePage,\n");
    buf.push_str("      codec: codec ?? defaultAppCodec,\n");
    buf.push_str("    );\n");

    buf
}
