use std::collections::HashMap;
use std::path::{Path, PathBuf};

use crate::micro_package::{to_camel_case, MicroPackageSlot};
use crate::parser::ModuleMetadata;

/// A micro-package composed into the host route registry.
#[derive(Debug, Clone)]
pub struct MicroPackageInfo {
    /// Generated module class, e.g. `FeatureShopKaiselModule`.
    pub class_name: String,
    /// Import URI used by the host's generated file.
    pub import_uri: String,
    /// Mount declarations, in declaration order.
    pub slots: Vec<MicroPackageSlot>,
}

impl MicroPackageInfo {
    /// Mount this micro-package declares as the host's landing route, if any.
    pub fn initial_slot(&self) -> Option<&MicroPackageSlot> {
        self.slots.iter().find(|slot| slot.is_initial)
    }
}

/// Joins a micro-package base prefix with a module prefix.
pub fn effective_prefix(base_prefix: Option<&str>, raw_prefix: &str) -> String {
    match base_prefix {
        Some(base) => {
            let base = base.trim_end_matches('/');
            let raw = raw_prefix.trim_start_matches('/');
            format!("{base}/{raw}")
        }
        None => raw_prefix.to_string(),
    }
}

/// A `package:` import for a file inside the package, so generated code does not
/// depend on where it sits relative to what it imports.
///
/// Falls back to the file's own path when it lies outside `lib_dir` or the
/// package name is unknown.
pub fn package_import(package_name: &str, lib_dir: &Path, file: &Path) -> String {
    if package_name.is_empty() {
        return file.to_string_lossy().replace('\\', "/");
    }
    match file.strip_prefix(lib_dir) {
        Ok(relative) => format!(
            "package:{package_name}/{}",
            relative.to_string_lossy().replace('\\', "/")
        ),
        Err(_) => file.to_string_lossy().replace('\\', "/"),
    }
}

pub fn generate_micro_package_code(
    module_name: &str,
    modules: &[ModuleMetadata],
    package_name: &str,
    lib_dir: &Path,
    base_prefix: Option<&str>,
) -> String {
    // Map each unique file_path to an import alias (i1, i2, ...)
    let mut unique_files: Vec<PathBuf> = modules
        .iter()
        .map(|m| m.file_path.clone())
        .collect();
    unique_files.sort();
    unique_files.dedup();

    let file_to_alias: HashMap<PathBuf, String> = unique_files
        .iter()
        .enumerate()
        .map(|(idx, path): (usize, &PathBuf)| (path.clone(), format!("i{}", idx + 1)))
        .collect();

    let mut buf = String::with_capacity(2048);

    buf.push_str("// GENERATED CODE - DO NOT MODIFY BY HAND\n");
    buf.push_str("// Generated by kaisel_generator\n\n");

    buf.push_str("import 'package:kaisel_generator/micro_mount.dart';\n\n");

    for file_path in &unique_files {
        let alias = &file_to_alias[file_path];
        buf.push_str(&format!(
            "import '{}' as {alias};\n",
            package_import(package_name, lib_dir, file_path)
        ));
    }
    buf.push('\n');

    let class_name = format!("{module_name}KaiselModule");
    buf.push_str(&format!("/// Micro-package module registry for `{module_name}`.\n"));
    buf.push_str("///\n");
    buf.push_str("/// Each declaration is a mount the host binds to one of its own marker\n");
    buf.push_str("/// routes, so no mount is ever resolved by name.\n");
    buf.push_str(&format!("abstract final class {class_name} {{\n"));

    for (idx, m) in modules.iter().enumerate() {
        let alias = &file_to_alias[&m.file_path];
        let field_name = to_camel_case(&m.mount_name);
        let route_type = format!("{alias}.{}", m.route_type);
        let codec_expr = match &m.codec_name {
            Some(c) => format!("{}.{}()", alias, c),
            None => format!("{}.{}Codec()", alias, m.route_type),
        };

        if idx > 0 {
            buf.push('\n');
        }
        buf.push_str(&format!(
            "  /// The mount this package contributes for `{}`.\n",
            m.mount_name
        ));
        buf.push_str(&format!(
            "  static const KaiselMicroMount<{route_type}> {field_name} =\n      KaiselMicroMount<{route_type}>(\n"
        ));
        if let Some(prefix) = &m.prefix {
            buf.push_str(&format!(
                "    prefix: '{}',\n",
                effective_prefix(base_prefix, prefix)
            ));
        }
        buf.push_str(&format!("    module: {}.{}(),\n", alias, m.class_name));
        buf.push_str(&format!("    codec: {codec_expr},\n"));
        if m.is_initial {
            buf.push_str("    isInitial: true,\n");
        }
        buf.push_str("  );\n");
    }

    buf.push_str("}\n");

    buf
}

pub fn generate_dart_code(
    modules: &[ModuleMetadata],
    route_class: &str,
    initial_route_override: Option<&str>,
    micro_packages: &[MicroPackageInfo],
    package_name: &str,
    lib_dir: &Path,
) -> String {
    // Map each unique file_path to an import alias (_i1, _i2, ...)
    let mut unique_local_files: Vec<PathBuf> = modules
        .iter()
        .map(|m| m.file_path.clone())
        .collect();
    unique_local_files.sort();
    unique_local_files.dedup();

    let file_to_alias: HashMap<PathBuf, String> = unique_local_files
        .iter()
        .enumerate()
        .map(|(idx, path): (usize, &PathBuf)| (path.clone(), format!("_i{}", idx + 1)))
        .collect();

    let mp_aliases: Vec<String> = (0..micro_packages.len())
        .map(|idx| format!("_mp{}", idx + 1))
        .collect();

    // Determine initial module mount name
    let marker_for = |slot: &MicroPackageSlot| slot.marker();
    let initial_mount = if let Some(custom_initial) = initial_route_override {
        custom_initial.to_string()
    } else if let Some(initial_module) = modules.iter().find(|m| m.is_initial) {
        initial_module.mount_name.clone()
    } else if let Some(micro_package_initial) = micro_packages
        .iter()
        .find_map(|mp| mp.initial_slot().map(marker_for))
    {
        micro_package_initial
    } else {
        modules
            .first()
            .map(|m| m.mount_name.clone())
            .unwrap_or_else(|| "HomeMount".to_string())
    };

    // Every mount needs a sealed subclass: the host's own, plus those only
    // declared by a micro-package's manifest.
    let mut all_mount_names: Vec<String> = Vec::new();
    for module in modules {
        if !all_mount_names.contains(&module.mount_name) {
            all_mount_names.push(module.mount_name.clone());
        }
    }
    for mp in micro_packages {
        for slot in &mp.slots {
            let name = marker_for(slot);
            if !all_mount_names.contains(&name) {
                all_mount_names.push(name);
            }
        }
    }

    // Routed host modules, longest prefix first so overlapping mounts compose.
    let mut routed_modules: Vec<&ModuleMetadata> = modules
        .iter()
        .filter(|m| m.prefix.is_some())
        .collect();
    routed_modules.sort_by(|a, b| {
        let len_a = a.prefix.as_ref().map(|p: &String| p.len()).unwrap_or(0);
        let len_b = b.prefix.as_ref().map(|p: &String| p.len()).unwrap_or(0);
        len_b.cmp(&len_a).then_with(|| a.mount_name.cmp(&b.mount_name))
    });

    let mut buf = String::with_capacity(4096);

    // Header
    buf.push_str("// GENERATED CODE - DO NOT MODIFY BY HAND\n");
    buf.push_str("// Generated by kaisel_generator\n\n");

    // Core Imports
    buf.push_str("import 'package:flutter/widgets.dart';\n");
    buf.push_str("import 'package:kaisel/kaisel.dart';\n");
    if !micro_packages.is_empty() {
        buf.push_str("import 'package:kaisel_generator/micro_mount.dart';\n");
    }
    buf.push('\n');

    // Micro-package manifest imports
    for (idx, mp) in micro_packages.iter().enumerate() {
        buf.push_str(&format!(
            "import '{}' as {};\n",
            mp.import_uri, mp_aliases[idx]
        ));
    }

    // Local Feature Module Imports with import aliases
    for file_path in &unique_local_files {
        let alias = &file_to_alias[file_path];
        buf.push_str(&format!(
            "import '{}' as {alias};\n",
            package_import(package_name, lib_dir, file_path)
        ));
    }
    buf.push('\n');

    // Route Sealed Class
    buf.push_str("// Host's sealed route hierarchy: one marker mount per feature module.\n");
    buf.push_str(&format!("sealed class {route_class} extends KaiselRoute {{\n"));
    buf.push_str(&format!("  const {route_class}();\n"));
    buf.push_str("}\n\n");

    // Individual Mount Subclasses (host modules and micro-package mounts alike)
    for mount_name in &all_mount_names {
        buf.push_str(&format!(
            "final class {mount_name} extends {route_class} {{\n  const {mount_name}();\n}}\n\n"
        ));
    }

    // Initial Route Constant
    buf.push_str("/// The default initial route for the host router.\n");
    buf.push_str(&format!(
        "const {route_class} kInitialAppRoute = {initial_mount}();\n\n"
    ));

    // Page Builder Switch
    buf.push_str("/// Dispatches each feature module inside a `KaiselModuleMount`.\n");
    buf.push_str(&format!(
        "Widget buildAppModulePage(BuildContext context, {route_class} route) => switch (route) {{\n"
    ));
    for m in modules {
        let alias = &file_to_alias[&m.file_path];
        buf.push_str(&format!(
            "  {}() => const KaiselModuleMount<{}.{}>(module: {}.{}()),\n",
            m.mount_name, alias, m.route_type, alias, m.class_name
        ));
    }
    for (idx, mp) in micro_packages.iter().enumerate() {
        for slot in &mp.slots {
            buf.push_str(&format!(
                "  {}() => {}.{}.{}.page,\n",
                slot.marker(),
                mp_aliases[idx],
                mp.class_name,
                slot.field_name
            ));
        }
    }
    buf.push_str("};\n\n");

    // Module Mounts List
    buf.push_str("/// Declarative module mounts for `ConfigCodecWithModules`.\n");
    if micro_packages.is_empty() {
        buf.push_str(&format!(
            "const List<ModuleMount<{route_class}>> appModuleMounts = [\n"
        ));
    } else {
        buf.push_str(&format!(
            "final List<ModuleMount<{route_class}>> appModuleMounts = [\n"
        ));
    }
    for m in &routed_modules {
        let alias = &file_to_alias[&m.file_path];
        let prefix = m.prefix.as_ref().unwrap();
        let codec_expr = match &m.codec_name {
            Some(c) => format!("{}.{}()", alias, c),
            None => format!("{}.{}Codec()", alias, m.route_type),
        };
        buf.push_str("  ModuleMount(\n");
        buf.push_str(&format!("    mountRoute: {}(),\n", m.mount_name));
        buf.push_str(&format!("    prefix: '{}',\n", prefix));
        buf.push_str(&format!("    codec: {},\n", codec_expr));
        buf.push_str("  ),\n");
    }
    for (idx, mp) in micro_packages.iter().enumerate() {
        for slot in mp.slots.iter().filter(|slot| slot.is_routed) {
            buf.push_str(&format!(
                "  {}.{}.{}.moduleMount(const {}()),\n",
                mp_aliases[idx],
                mp.class_name,
                slot.field_name,
                slot.marker()
            ));
        }
    }
    buf.push_str("];\n\n");

    // Route Encoder Helper
    buf.push_str("/// Encodes host mount markers to their canonical URLs.\n");
    buf.push_str(&format!(
        "Uri? encodeAppModuleRoute({route_class} route) => switch (route) {{\n"
    ));
    for m in modules {
        let path = match &m.prefix {
            Some(p) => p.as_str(),
            None => "/",
        };
        buf.push_str(&format!("  {}() => Uri(path: '{}'),\n", m.mount_name, path));
    }
    for (idx, mp) in micro_packages.iter().enumerate() {
        for slot in &mp.slots {
            buf.push_str(&format!(
                "  {}() => {}.{}.{}.url,\n",
                slot.marker(),
                mp_aliases[idx],
                mp.class_name,
                slot.field_name
            ));
        }
    }
    buf.push_str("};\n\n");

    // Default Base App Codec
    buf.push_str("/// Default host codec delegating unmounted paths to the initial route.\n");
    buf.push_str(&format!(
        "class DefaultBaseAppCodec extends KaiselConfigCodec<{route_class}> {{\n"
    ));
    buf.push_str("  const DefaultBaseAppCodec();\n\n");
    buf.push_str(&format!(
        "  @override\n  KaiselConfig<{route_class}>? decode(Uri uri) {{\n"
    ));
    buf.push_str("    final segments = uri.pathSegments\n");
    buf.push_str("        .where((segment) => segment.isNotEmpty)\n");
    buf.push_str("        .toList(growable: false);\n\n");
    buf.push_str("    return switch (segments) {\n");
    buf.push_str("      [] => KaiselConfig(mainStack: const [kInitialAppRoute]),\n");
    buf.push_str("      _ => null,\n");
    buf.push_str("    };\n  }\n\n");
    buf.push_str(&format!(
        "  @override\n  Uri encode(KaiselConfig<{route_class}> config) {{\n"
    ));
    buf.push_str("    final uri = encodeAppModuleRoute(config.mainStack.last);\n");
    buf.push_str("    return uri ?? Uri(path: '/');\n  }\n");
    buf.push_str("}\n\n");

    // Codec Constants
    buf.push_str("/// Complete composite URL codec bundling `DefaultBaseAppCodec` and `appModuleMounts`.\n");
    if micro_packages.is_empty() {
        buf.push_str(&format!(
            "const defaultAppCodec = ConfigCodecWithModules<{route_class}>(\n"
        ));
        buf.push_str("  baseCodec: DefaultBaseAppCodec(),\n");
        buf.push_str("  modules: appModuleMounts,\n");
        buf.push_str(");\n\n");
    } else {
        buf.push_str(&format!(
            "final defaultAppCodec = ConfigCodecWithModules<{route_class}>(\n"
        ));
        buf.push_str("  baseCodec: const DefaultBaseAppCodec(),\n");
        buf.push_str("  modules: appModuleMounts,\n");
        buf.push_str(");\n\n");
    }

    // Router Configuration
    buf.push_str("/// Ready-to-use default router configuration for the host app.\n");
    buf.push_str(&format!(
        "final defaultAppRouterConfig = KaiselRouterConfig<{route_class}>(\n"
    ));
    buf.push_str("  initial: kInitialAppRoute,\n");
    buf.push_str("  builder: buildAppModulePage,\n");
    buf.push_str("  codec: defaultAppCodec,\n");
    buf.push_str(");\n\n");

    // Custom Config Builder
    buf.push_str("/// Convenience factory for customizing host router configuration.\n");
    buf.push_str(&format!(
        "KaiselRouterConfig<{route_class}> createAppRouterConfig({{\n"
    ));
    buf.push_str(&format!("  {route_class}? initial,\n"));
    buf.push_str(&format!("  KaiselPageBuilder<{route_class}>? builder,\n"));
    buf.push_str(&format!("  KaiselConfigCodec<{route_class}>? codec,\n"));
    buf.push_str("}) =>\n");
    buf.push_str(&format!("    KaiselRouterConfig<{route_class}>(\n"));
    buf.push_str("      initial: initial ?? kInitialAppRoute,\n");
    buf.push_str("      builder: builder ?? buildAppModulePage,\n");
    buf.push_str("      codec: codec ?? defaultAppCodec,\n");
    buf.push_str("    );\n");

    buf
}

#[cfg(test)]
mod tests {
    use super::*;

    fn shop_module() -> ModuleMetadata {
        ModuleMetadata {
            class_name: "ShopRouterModule".to_string(),
            route_type: "ShopRoute".to_string(),
            mount_name: "ShopMount".to_string(),
            prefix: Some("/shop".to_string()),
            is_initial: false,
            codec_name: Some("ShopRouteCodec".to_string()),
            file_path: PathBuf::from("lib/features/shop/shop_module.dart"),
        }
    }

    fn home_module() -> ModuleMetadata {
        ModuleMetadata {
            class_name: "HomeRouterModule".to_string(),
            route_type: "HomeRoute".to_string(),
            mount_name: "HomeMount".to_string(),
            prefix: None,
            is_initial: true,
            codec_name: None,
            file_path: PathBuf::from("lib/features/home/home_module.dart"),
        }
    }

    fn external_feature_shop() -> MicroPackageInfo {
        MicroPackageInfo {
            class_name: "FeatureShopKaiselModule".to_string(),
            import_uri: "package:feature_shop/feature_shop.kaisel.dart".to_string(),
            slots: vec![
                MicroPackageSlot {
                    field_name: "shopMount".to_string(),
                    is_routed: true,
                    is_initial: false,
                    host_marker: String::new(),
                },
                MicroPackageSlot {
                    field_name: "cartMount".to_string(),
                    is_routed: true,
                    is_initial: false,
                    host_marker: String::new(),
                },
            ],
        }
    }

    #[test]
    fn test_manifest_declares_typed_mounts() {
        let code = generate_micro_package_code(
            "FeatureShop",
            &[home_module(), shop_module()],
            "feature_shop",
            Path::new("lib"),
            Some("/shop"),
        );

        assert!(code.contains("import 'package:kaisel_generator/micro_mount.dart';"));
        // Module files are imported by package URI, never relatively.
        assert!(code.contains("import 'package:feature_shop/features/home/home_module.dart' as i1;"));
        assert!(code.contains("import 'package:feature_shop/features/shop/shop_module.dart' as i2;"));
        // Each mount is a typed declaration; the host binds it to its own route.
        assert!(code.contains("static const KaiselMicroMount<i1.HomeRoute> homeMount ="));
        assert!(code.contains("static const KaiselMicroMount<i2.ShopRoute> shopMount ="));
        assert!(code.contains("    module: i2.ShopRouterModule(),"));
        assert!(code.contains("    codec: i2.ShopRouteCodec(),"));
        assert!(code.contains("    prefix: '/shop/shop',"));
        assert!(code.contains("    isInitial: true,"));
        // No names for a host to dispatch on are generated at all.
        assert!(!code.contains("mountNames"));
        assert!(!code.contains("buildPage("));
        assert!(!code.contains("mounts<"));
    }

    #[test]
    fn test_manifest_omits_is_initial_and_prefix_when_not_set() {
        let code = generate_micro_package_code(
            "FeatureShop",
            &[shop_module()],
            "feature_shop",
            Path::new("lib"),
            None,
        );

        assert!(!code.contains("isInitial"));
        assert!(code.contains("    prefix: '/shop',"));
    }

    #[test]
    fn test_host_composes_external_micro_package() {
        let code = generate_dart_code(
            &[home_module()],
            "AppRoute",
            None,
            &[external_feature_shop()],
            "host_app",
            Path::new("lib"),
        );

        assert!(code.contains("import 'package:kaisel_generator/micro_mount.dart';"));
        // Host modules are imported by package URI, never relatively.
        assert!(code.contains("import 'package:host_app/features/home/home_module.dart' as _i1;"));
        // Manifest is imported through its package URI, not a relative path.
        assert!(code.contains(
            "import 'package:feature_shop/feature_shop.kaisel.dart' as _mp1;"
        ));
        // External mounts get host-side sealed subclasses, including mounts the host never scanned.
        assert!(code.contains("final class ShopMount extends AppRoute"));
        assert!(code.contains("final class CartMount extends AppRoute"));
        // Pages are delegated to the package's typed declaration.
        assert!(code.contains("ShopMount() => _mp1.FeatureShopKaiselModule.shopMount.page,"));
        assert!(code.contains("CartMount() => _mp1.FeatureShopKaiselModule.cartMount.page,"));
        // The host binds each declaration to its own marker instance.
        assert!(code.contains(
            "_mp1.FeatureShopKaiselModule.shopMount.moduleMount(const ShopMount()),"
        ));
        assert!(code.contains(
            "_mp1.FeatureShopKaiselModule.cartMount.moduleMount(const CartMount()),"
        ));
        // URLs come from the declaration instead of a host-side copy of the prefix.
        assert!(code.contains("CartMount() => _mp1.FeatureShopKaiselModule.cartMount.url,"));
        assert!(!code.contains("_createExternalMountRoute"));
        // The host still owns the routes it scanned directly.
        assert!(code.contains(
            "HomeMount() => const KaiselModuleMount<_i1.HomeRoute>(module: _i1.HomeRouterModule()),"
        ));
    }

    #[test]
    fn test_external_initial_mount_becomes_initial_route() {
        let mut micro_package = external_feature_shop();
        micro_package.slots[0].is_initial = true;

        let code = generate_dart_code(
            &[],
            "AppRoute",
            None,
            &[micro_package],
            "host_app",
            Path::new("lib"),
        );

        assert!(code.contains("const AppRoute kInitialAppRoute = ShopMount();"));
    }

    #[test]
    fn test_host_without_micro_packages_stays_const() {
        let code = generate_dart_code(
            &[home_module(), shop_module()],
            "AppRoute",
            None,
            &[],
            "host_app",
            Path::new("lib"),
        );

        assert!(code.contains("const List<ModuleMount<AppRoute>> appModuleMounts = ["));
        assert!(!code.contains("micro_mount"));
    }
}
