import 'package:kaisel_generator/src/parser/manifest_parser.dart';
import 'package:test/test.dart';

void main() {
  const parser = ManifestParser();

  test('should read the mount a generated manifest declares', () {
    final manifest = parser.parse('''
// GENERATED CODE - DO NOT MODIFY BY HAND
// Generated by kaisel_generator

import 'package:kaisel_generator/micro_mount.dart';

import 'package:profile/profile.dart' as i1;

/// Micro-package module registry for `Profile`.
///
/// Each declaration is a mount the host binds to one of its own marker
/// routes, so no mount is ever resolved by name.
abstract final class ProfileKaiselModule {
  /// The mount this package contributes for `ProfileMount`.
  static const KaiselMicroMount<i1.ProfileRoute> profileMount =
      KaiselMicroMount<i1.ProfileRoute>(
    prefix: '/profile',
    module: i1.ProfileRouterModule(),
    codec: i1.ProfileRouteCodec(),
  );
}
''');

    expect(manifest, isNotNull);
    expect(manifest!.className, 'ProfileKaiselModule');
    expect(manifest.mounts, hasLength(1));

    final mount = manifest.mounts.single;
    expect(mount.fieldName, 'profileMount');
    expect(mount.mountName, 'ProfileMount');
    expect(mount.marker, 'ProfileMount');
    expect(mount.isRouted, isTrue);
    expect(mount.isInitial, isFalse);
  });

  test('should read every declaration, with the landing mount marked', () {
    final manifest = parser.parse('''
abstract final class FeatureShopKaiselModule {
  static const KaiselMicroMount<i1.ShopRoute> homeMount =
      KaiselMicroMount<i1.ShopRoute>(
    module: i1.ShopRouterModule(),
    codec: i1.ShopRouteCodec(),
    isInitial: true,
  );

  static const KaiselMicroMount<i1.CartRoute> cartMount =
      KaiselMicroMount<i1.CartRoute>(
    prefix: '/cart',
    module: i1.CartRouterModule(),
    codec: i1.CartRouteCodec(),
  );
}
''');

    expect(manifest!.mounts, hasLength(2));

    final home = manifest.mounts.first;
    expect(home.fieldName, 'homeMount');
    expect(home.isRouted, isFalse);
    expect(home.isInitial, isTrue);

    final cart = manifest.mounts.last;
    expect(cart.fieldName, 'cartMount');
    expect(cart.isRouted, isTrue);
    expect(cart.isInitial, isFalse);
  });

  test('should reject a source that is not a manifest', () {
    expect(parser.parse('// stale manifest\n'), isNull);
    expect(parser.parse('class SomethingKaiselModule {}'), isNull);
  });
}
